/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
  theme: {
    extend: {
      fontFamily: {
        torus: [
          "Torus",
          "Inter",
          "Helvetica Neue",
          "Tahoma",
          "Arial",
          "Hiragino Kaku Gothic ProN",
          "Meiryo",
          "Microsoft YaHei",
          "Apple SD Gothic Neo",
        ],
        play: ["Play"],
      },
    },
  },
  plugins: [require("daisyui")],
};
