/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
  theme: {
    extend: {
      fontFamily: {
        torus: [
          "Torus",
          "Inter",
          "Helvetica Neue",
          "Tahoma",
          "Arial",
          "Hiragino Kaku Gothic ProN",
          "Meiryo",
          "Microsoft YaHei",
          "Apple SD Gothic Neo",
        ],
      },
    },
    colors: {
      "blue-gray": "#414558",
      "hot-pink": "#ff79c6",
      "mid-purple": "#bd93f9",
      "warm-yellow": "#ffb86c",
      "indigo-200": "#c7d2fe",
      "indigo-600": "#4f46e5",
      "slate-300": "#c7d2fe",
    },
  },
  plugins: [require("daisyui")],
};
